Unit test
Hebbe1234/P3 pull request #53
Opened 2020-11-12 10:27 UTC by Hebbe1234

Made unit tests
Changed all managers to DI
Deleted DatabaseManager
Added Context as DI in entities 
Fixed unit tests

2020-11-12 10:38 UTC, mart648g requested changes
Edie venue medfører at den crasher når den prøver at gemme det.

Den er markant langsommere, fordi der ved hvert eneste click laves en ny festivalmanager, hvori der laves en ny calender, og alt information skal derefter hentes ned fra en databasen.

2020-11-12 11:02 UTC, Hebbe1234 commented
Jeg valgte, at fjerne DB initialiseringen

2020-11-12 11:06 UTC, mart648g requested changes
Error when making new user. (Liste af legal tickets: 2 3 4 5 .... 20)

2020-11-12 11:16 UTC, Hebbe1234 commented
> Error when making new user. (Liste af legal tickets: 2 3 4 5 .... 20)

Kan du uddybe det her?

2020-11-12 11:28 UTC, goldflue commented on NorthernWinterBeat/NorthernWinterBeat/Pages/MakeUserLogin.cshtml.cs
> +        }
Hvorfor er det at DataAccess ikke skal inkluderes i den her?

2020-11-12 11:30 UTC, goldflue commented on NorthernWinterBeat/NorthernWinterBeatLibrary/Managers/AuthorizationManager.cs
> +            if (t2.Count() == 0)
vi bør måske overveje anden navngivning til t1 og t2 variablene.

2020-11-12 11:31 UTC, goldflue commented on NorthernWinterBeat/NorthernWinterBeatLibrary/Managers/NorthernWinterBeatConcertContext.cs
> +           //Please do not bully me for changing my stance on the DB initialization
brace yourself 😈😈😈

2020-11-12 11:32 UTC, goldflue commented on NorthernWinterBeat/NorthernWinterBeatLibrary/Managers/NorthernWinterBeatConcertContext.cs
> +        public virtual DbSet<ApplicationUser> ApplicationUser { get; set; }
Hvorfor skal de være virtual?

2020-11-12 11:36 UTC, goldflue approved these changes
Nice - kan generelt kun finde små ting / spørgsmål til det som er ændret.

2020-11-13 07:27 UTC, mart648g commented
![image](https://user-images.githubusercontent.com/56824309/99040684-d9d08200-2589-11eb-924a-73b76b406169.png)
Når en ny bruger laves, opstår der en nullreferenceexception, i MakeUserLogin.

2020-11-13 07:36 UTC, mart648g approved these changes
Det virker som om det virker

2020-11-13 11:37 UTC, merged